# Generated by Django 6.0 on 2025-12-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_billed',
            field=models.BooleanField(default=False),
        ),
    ]
